"""Autogenerated initial: create_all via metadata (baseline for SQLite/Postgres)."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision = "0001_init"
down_revision = None
def upgrade():
    op.create_table("documents",
        sa.Column("id", sa.String(), primary_key=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("nosology", sa.String(), nullable=False),
        sa.Column("icd10_codes", sa.JSON(), default=list),
        sa.Column("approval_year", sa.Integer(), default=2024),
        sa.Column("revision_year", sa.Integer(), nullable=True),
        sa.Column("source_file", sa.String(), default=""),
        sa.Column("status", sa.String(), default="processed"),
        sa.Column("data", sa.JSON(), default=dict),
        sa.Column("full_text", sa.Text(), default=""),
        sa.Column("confidence", sa.String(), default="medium"),
        sa.Column("needs_review", sa.Boolean(), default=False),
        sa.Column("created_at", sa.DateTime(), nullable=True))
    op.create_table("query_log",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("query", sa.Text(), default=""),
        sa.Column("intent", sa.String(), default=""),
        sa.Column("refused", sa.Boolean(), default=False),
        sa.Column("created_at", sa.DateTime(), nullable=True))
    op.create_table("favorites",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("user", sa.String(), default="doctor"),
        sa.Column("doc_id", sa.String(), default=""),
        sa.Column("note", sa.String(), default=""))
def downgrade():
    op.drop_table("favorites"); op.drop_table("query_log"); op.drop_table("documents")
